# Generated by Django 4.0.5 on 2022-07-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_category_register_subadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=200)),
                ('c_email', models.EmailField(default='', max_length=200)),
                ('c_cno', models.CharField(default='', max_length=50)),
                ('c_add', models.TextField(default='')),
                ('join_date', models.DateField(auto_now=True, null=True)),
                ('profile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Com_Prof/')),
                ('c_pass', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
