# Generated by Django 4.0.5 on 2022-07-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_companydetail_c_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='c_email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='c_pass',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nm', models.CharField(default='', max_length=200)),
                ('prod_price', models.PositiveIntegerField(default=0)),
                ('prod_qty', models.PositiveIntegerField(default=0)),
                ('prod_img', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='ProductPic/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_nm', models.CharField(default='', max_length=200)),
                ('cust_em', models.EmailField(default='', max_length=200)),
                ('cust_con', models.CharField(default='', max_length=50)),
                ('cust_add1', models.TextField(default='')),
                ('cust_add2', models.TextField(default='')),
                ('cust_pass', models.CharField(default='', max_length=200)),
                ('cust_regi_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cust_profile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Cust_Pic/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companydetail')),
            ],
        ),
    ]
